package net.d4rk.inventorychef.constants;

public class Constants {
    public static final String[] INGREDIENT_SUGGESTIONS = new String[] {
            // Netto
            "Paprika",
            "Karotten",
            "Knoblauch",
            "Zwiebeln",
            "Maiskolben",
            "Broccoli",
            "Blumenkohl",
            "Kürbis",
            "Maiskolben",
            "Tomaten",
            "Kohlrabi",
            "Gurken",
            "Radieschen",
            "Zuckererbsen",
            "Pilze",
            "Kartoffel",
            "Süßkartoffeln",
            "Rote Beete",
            "Stangenbohnen",
            "Salat",
            "Rucola",
            "Ingwer",
            "Avocado",
            "Zucchini",
            "Suppengrün",
            "grüner Spargel",
            "Apfel",
            "Trauben",
            "Erdbeeren",
            "Himbeeren",
            "Bananen",
            "Kirschen",
            "Wassermelone",
            "Passionsfrucht",
            "Zitrone",
            "Physalis",
            "Kiwi",
            "Aprikosen",
            "Rhabarber",
            "Mango",
            "Heidelbeeren",
            "Nekarinen",
            "Ananas",
            "Clementinen",
            "Pomelo",

            "Saft",
            "Smoothie",

            "Kopierpapier",
            "Versandtaschen",
            "Briefumschläge",
            "Müllbeutel",
            "Biomüllbeutel",
            "Kosmetikbeutel",
            "Taschentücher",
            "Deo",
            "Waschmittel",
            "Weichspüler",
            "Anti-Kalk",
            "Spülmaschinenpulver",
            "Klarspüler",
            "Spezialsalz",
            "Badreiniger",
            "Essigreiniger",
            "Seife",
            "Klopapier",
            "Zewa",
            "Wischtücher",
            "Schwammtuch",

            "Salz",
            "Pesto",
            "Suppennudeln",
            "Buchstabennudeln",
            "Mehl",
            "Vollkornmehl",
            "Haselnüsse",
            "Mandeln",
            "gem. Haselnüsse",
            "gem. Mandeln",
            "Zucker",
            "Rohrzucker",
            "Puderzucker",
            "Gelierzucker",
            "Schokoladenpudding",
            "Vanillepudding",
            "Vanillinzucker",
            "Kakao",
            "Kuchenglasur",
            "Speisestärke",
            "Blockschokolade",
            "Backpulver",
            "Rum-Aroma",
            "Linsen",

            "Milchbrötchen",
            "Kaba",
            "Kaffee",
            "Kaffeepads",
            "Cappuchino",
            "haltb. Sahne",
            "Schokocreme",
            "Toast",
            "Honig",
            "Sanella",

            "Joghurt",
            "Fruchtjoghurt",
            "Skyr",
            "Saure Sahne",
            "Creme Fraiche",
            "Mascarpone",
            "Quark",
            "Butter",
            "ges. Butter",
            "Käseaufschnitt",
            "Cheddar",
            "ger. Käse",
            "herzh. Käse",
            "Weichkäse",
            "Frischkäse",
            "Mozzarella",
            "Ofenkäse",
            "Grillkäse",
            "Babybel",
            "Tortelloni",
            "Schupfnudeln",
            "Hirtenkäse",
            "Parmesan",
            "Gouda",
            "gef. Pepperoni",
            "Ketchup",
            "Mayonaise",
            "Hefe",
            "Seelachsschnitzel",
            "Pizzateig",
            "Senf",

            "Salami",
            "Schinken",
            "Baconstreifen",
            "Schinkenwürfel",
            "Hackfleisch",
            "Minutensteaks",
            "Grillfackeln",
            "Weißwurst",

            "Kokosmilch",
            "Ajvar",
            "Laugenstangen",
            "Laugenbrezen",
            "Tiefkühlkräuter",
            "Pommes Frites",
            "Fischstäbchen",
            "Backfisch",
            "Seelachs",

            "Apfelmus",
            "Ananasscheiben",
            "Pfirsiche",
            "Mandarinen",
            "Kidneybohnen",
            "Baked Beans", // alle Bohnen
            "...bohnen",
            "",
            "Kichererbsen",
            "Gemüsemais",
            "passierte Tomaten",
            "Tomatenwürfel",
            "Maiskölbchen",
            "Cornichons",
            "Eis",

            "Sonnenblumenöl",
            "Keimöl",
            "Essig",
            "Balsamicoessig",
            "Balsamicoessig weiß",
            "Wein",
            "Milch",
            "Cornflakes",
            "Müsli",
            "Haferflocken fein",
            "Haferflocken grob",
            "Dinkelknusper",
            "Porridge",
            "Wraps",
            "Chiasamen",
            "Walnüsse",
            "Cashewkerne",
            "Pistazien",
            "Cantuccini",
            "Snyders",
            "Chips",
            "Pombär Chips",
            "Hafercookies",
            "Vitalgebäck",
            "Amarettini",
            "Grissini",
            "Minichoc",

            "Karamalz",
            "Hefeweizen",
            "Radler",

            "Gummibären",
            "Schokolade",
            "Nippon",
            "BallaSticks",
            "Toffifee",

            "Zwieback",
            "Knäckebrot",

            // LIDL
            "Wok-Gemüse",
            "Italienische Haselnüsse",
            "Paranüsse",

            // dm
            "Bulgur",
            "Couscous",
            "Hirse",
            "Quinoa",
            "Polenta",
            "Lankornreis",
            "Parboiled Reis",
            "Risottoreis",
            "Milchreis",
            "...reis",  // weitere Reissorten
            "Vollkornmehl",
            "Dinkelvollkornmehl",
            "Magnesium",
            "Calcium",
            "Honigwaffeln",
            "Erdnussmus",
            "Nussmus",

            // denn's
            "Gemüsebrühe",
            "Farfalle",
            "Spaghetti",
            "Lasagneplatten"
    };
}
